name: My First Workflow

env:
  APP: test
  APPLICATION_REPOSITORY: basma1912/testActions


on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  MyFirstJob:
     runs-on: ubuntu-latest
     steps:
       - run: echo "👋 Hello World! ✌️ "

       - name: Checkout
         uses: actions/checkout@v4.1.7
         with: 
          repository: ${{ env.APPLICATION_REPOSITORY }}

       - name: List files in respository
         run: |
          echo "The repository ${{ github.repository }} contains the following files: "
          tree 
      
 
 
