name: My First Workflow

env:
  APP: test
  APPLICATION_REPOSITORY: basma1912/ActionInAction


on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  MyFirstJob:
     permissions: write-all
     runs-on: ubuntu-latest
     steps:
       - run: echo "👋 Hello World! ✌️ "

       - name: Checkout
         uses: actions/checkout@v4.1.7
         with: 
          repository: ${{ env.APPLICATION_REPOSITORY }}

       - name: List files in respository
         run: |
          echo "The repository ${{ env.APPLICATION_REPOSITORY }} contains the following files: "
          tree 

       - name: copy file from repo x to repo y
         run: |
          mv the_file.yaml textx.yaml
          echo "whatever"
          git add textx.yaml
          git commit -m "this is a commit"
          gh pr create --title "The fix" --body "This fixes the issue" --head "try01" --base "main" --repo "basma1912/ActionInAction"
         env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
 
 
