name: My First Workflow

env:
  APP: test
  APPLICATION_REPOSITORY: basma1912/testA


on:
  push:
    branches:
      - main
      
  workflow_dispatch:
jobs:
  MyFirstJob:
     permissions: write-all
     runs-on: ubuntu-latest
     steps:
       - run: echo "👋 Hello World! ✌️ "

       - name: Checkout
         uses: actions/checkout@v4.1.7
         with: 
          repository: ${{ env.APPLICATION_REPOSITORY }}

       - name: List files in respository
         run: |
          echo "The repository ${{ env.APPLICATION_REPOSITORY }} contains the following files: "
          tree 

       - name: copy file from repo x to repo y
         run: |
          mv the_file.yaml testx.yaml
          cp testx.yaml /tmp/
          echo "whatever the first time"
          tree
          pwd
          cat /tmp/testx.yaml
         env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
       - name : checkout infra repo
         uses: actions/checkout@v4.1.7
         with:
          repository : basma1912/testActions
       - name: doing the work 
         run: |
          echo "whatever the second time "
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          gh api -H 'Accept: application/vnd.github.v3.raw' "repos/basma1912/testA/contents/the_file.yaml" > ./LOCAL-FILE
          cat ./LOCAL-FILE
          git checkout -b try001
          git add .
          git commit -m "New post"
          git push -u origin try001
          
         env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  
          
         
     
         
 
 
